### ISSUE TITLE
cloud TODO

### ISSUE THREAD

**Issue by mdsumner** [DataScienceHobart/2017-01-31-resbaztas-r#3]
The latest image is "comic scrubbird"

- [x] set the CRAN mirror (so that shell users install packages don't have to do it)
- [x] check packages we need are installed anyway
- [x] put the shell and R files needed in the VM (python stream has "/home/researcher/data-shell"
- [x] update system
- [x] update R packages
- [x] install sqlite3
- [x] install packages - ggplot2, plyr, gapminder, tidyr, dplyr
- [x]  save image

tick tickety tick

echo 'local({ r <- getOption("repos"); r["CRAN"] <- "https://cran.ms.unimelb.edu.au/";options(repos = r); })' >> /etc/R/Rprofile.site

# Lessons

We start here at **R for Reproducible Scientific Analysis**: 

http://swcarpentry.github.io/r-novice-gapminder/

http://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/

http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/

**Comment by mdsumner** [comment]
users can create github account but not confirm the email

resbaz will request auth first time 

user doesnt get anything CREATED

**Comment by mdsumner** [comment]
The Python image is "serene bristlebird", and Mike's instance of it is "affectionate moorhen"

**Comment by mdsumner** [comment]
need tidyverse, devtools, formatR, raster, rgdal, ncdf4, RNetCDF, sf, maptools, rworldmap, maps

spatial stuff, devtools: 

apt-get install libnetcdf-dev netcdf-bin proj-bin libproj-dev libgdal-dev  gdal-bin  libgeos-dev libssl-dev

"elated finch" begat "empathetic kookaburra"

had to clean up 

"empathetic kookaburra" begat "proud baza"

**Comment by mdsumner** [comment]
add roxygen2

put in the data/ directory
download.file("https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder-FiveYearData.csv", destfile = "data/gapminder-FiveYearData.csv")



"proud baza" begat "flippant shelduck"

**Comment by mdsumner** [comment]
Be sure to delete the hidden directories created by RStudio, before you save them,  these are called .config and .rstudio. 

Otherwise, don't save images, just record the script to customize the original and do it that way!

:)
